# This default profile is used when running a single instance completely standalone:
spring:
  security:
    user:
      name: eureka
      password: secret
  config:
    activate:
      on-profile: default
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: discovery-server
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false    expected-client-renewal-interval-seconds: 1
    eviction-interval-timer-in-ms: 3
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'  
 
---
spring:
  security:
    user:
      name: eureka
      password: secret
  config:
    activate:
      on-profile: peer-1
  application:
    name: eureka-server-clustered
  zipkin:
    base-url: http://10.103.12.11:9411/
server:
  port: 9090
eureka:
  instance:
    hostname: eforms1.nic.in  
    lease-expiration-duration-in-seconds: 2 
  client:
    registerWithEureka: true
    fetchRegistry: true       
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka:secret@eforms2.nic.in:9091/eureka/,http://eureka:secret@eforms3.nic.in:9092/eureka/
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 1
    eviction-interval-timer-in-ms: 3
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
 
---
spring:
  security:
    user:
      name: eureka
      password: secret
  config:
    activate:
      on-profile: peer-2
  application:
    name: eureka-server-clustered   
  zipkin:
    base-url: http://10.103.12.11:9411/
server:
  port: 9091
eureka:
  instance:
    hostname: eforms2.nic.in     
    lease-expiration-duration-in-seconds: 30  
  client:
    registerWithEureka: true
    fetchRegistry: true    
    initial-instance-info-replication-interval-seconds: 5   
    serviceUrl:
      defaultZone: http://eureka:secret@eforms1.nic.in:9090/eureka/,http://eureka:secret@eforms3.nic.in:9092/eureka/
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 1
    eviction-interval-timer-in-ms: 3
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
 
---
spring:
  security:
    user:
      name: eureka
      password: secret
  config:
    activate:
      on-profile: peer-3
  application:
    name: eureka-server-clustered  
  zipkin:
    base-url: http://10.103.12.11:9411/
server:
  port: 9092
eureka:
  instance:
    hostname: eforms3.nic.in
    lease-expiration-duration-in-seconds: 30   
  client:
    registerWithEureka: true
    fetchRegistry: true
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka:secret@eforms1.nic.in:9090/eureka/,http://eureka:secret@eforms2.nic.in:9091/eureka/
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 1
    eviction-interval-timer-in-ms: 3
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 