<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>eForms : Email OTP</title>
</head>
<body>
<div style="margin:auto;max-width:991px">
	<div style="color: #fff;"><h1 style="background: #4c83ee;padding: 5px 15px;border-radius: 3px;">Greetings, ${message.email}</h1></div>
	<div style="margin-top: 10px">Your message is <b>${message.emailContent}</b></div>
	<div style="margin-top: 10px"> Have a nice day..!</div>
</div>
</body>
</html>