package in.nic.ashwini.eForms.utils;

import org.springframework.stereotype.Component;

@Component
public class Constants {
	public static final String PROFILE_TABLE = "user_profile";
    public static final String EMAIL = "email";
    public static final String MOBILE = "mobile";
    public static final String STATE_TABLE = "district";
    public static final String STATUS_TABLE = "status";
    public static final String ADMIN_TABLE = "support_individual_login";
    public static final String SUPPORT_TABLE = "support_ip";
    public static final String COORDINATOR_TABLE = "coordinators_services";
    public static final String COORDINATOR_REGISTRATION_TABLE = "coordinator_registration";
    public static final String SUPERUSER_TABLE = "coordinator_list_status";
    public static final String ORGANIZATION_TABLE = "employment_organization";
    public static final String VPN_COORDINATOR_TABLE = "vpn_coordinator";
    public static final String COORDINATOR_EMAIL = "emp_coord_email";
    public static final String EMAIL_COLUMN_FOR_SUPPORT_ADMIN = "user_name";
    public static final String RO_TABLE = "nicemployee_reporting";
    public static final String OTP_TABLE = "otp_save";
    public static final String CA_TABLE = "comp_auth";
    public static final String DASHBOARD_TABLE = "dashboard_admin";
    public static final String DA_PENDING = "Pending with DA-Admin"; // line added by pr on 20thfeb18
    public static final String RELAY_FORM_KEYWORD = "relay";
    public static final String BULK_TABLE_NAME = "bulk_registration";
    public static final String DIST_TABLE_NAME = "distribution_registration";
    public static final String SMS_FORM_KEYWORD = "sms";
    public static final String RELAY_TABLE_NAME = "relay_registration";
    public static final String ROLE_USER = "user"; // line added by pr on 10thapr18
    public static final String ROLE_DA = "da"; // line added by pr on 10thapr18
    public static final String MOB_TABLE_NAME = "mobile_registration";
    public static final String MAIL_ADMIN_PENDING = "Pending with Admin";
    public static final String DNS_FORM_KEYWORD = "dns";
    public static final String ROLE_CA = "ca";
    public static final String MOB_FORM_KEYWORD = "mobile";
    public static final String manual_upload = "Pending with User"; // line added by meenaxi/nikki 6 mar
    public static final String DNS_MAILADMIN = "preeti.nhq@nic.in";
    public static final String NKN_TABLE_NAME = "nkn_registration";
    public static final String NKN_SINGLE_FORM_KEYWORD = "nkn_single";
    public static final String CANCEL = "Cancelled";
    public static final String IP_TABLE_NAME = "ip_registration";
    public static final String SMS_TABLE_NAME = "sms_registration";
    public static final String SINGLE_TABLE_NAME = "single_registration";
    public static final String US_REJECTED = "Rejected by Under Secretary and above";
    public static final String IMAP_FORM_KEYWORD = "imappop";
    public static final String ROLE_CO = "co";
    public static final String VPN_TABLE_NAME = "vpn_registration";
    public static final String VPN_SURRENDER_FORM_KEYWORD = "vpn_surrender";
    public static final String VPN_DELETE_FORM_KEYWORD = "vpn_delete";
    //public static final String SECOND_COORD = "seema@gov.in,rajesh.singh@gov.in,rajp@nic.in";// to be uncommented in production
    public static final String DNS_SECOND_COORD = "preeti.nhq@nic.in,rahejapreeti@hotmail.com,rahejapreeti@gmail.com";
    public static final String VPN_SINGLE_FORM_KEYWORD = "vpn_single";
    public static final String CENTRAL_UTM_FORM_KEYWORD = "centralutm";
    public static final String BULK_FORM_KEYWORD = "bulk";
    public static final String VPN_MAILADMIN = "preeti.nhq@nic.in,rahejapreeti@hotmail.com,rahejapreeti@gmail.com"; // line added by pr on 29thdec17
    public static final String GEM_TABLE_NAME = "gem_registration";
    public static final String PENDING_API = "Pending with API"; // line added by meenaxi/nikki 6 mar
    public static final String DNS_TABLE_NAME = "dns_registration";
    public static final String ROLE_MAILADMIN = "admin";
    public static final String STAT_REMARKS_TEXT = "AlphaNumeric Characters allowed with special characters like ( # , . - : / ' @ & \\ _ ?) with maximum length 500 characters "; // line added by pr on 28thdec18
    public static final String LDAP_FORM_KEYWORD = "ldap";
    public static final String WIFI_FORM_KEYWORD = "wifi";
    public static final String VPN_ADD_FORM_KEYWORD = "change_add";
    public static final String VPN_RENEW_FORM_KEYWORD = "vpn_renew";
    public static final String WEBCAST_TABLE_NAME = "webcast_registration";
    public static final String WEBCAST_FORM_KEYWORD = "webcast";
    public static final String FIREWALL_TABLE_NAME = "centralutm_registration";
    public static final String FIREWALL_FORM_KEYWORD = "centralutm";
    public static final String EMAILACTIVATE_FORM_KEYWORD = "email_act";
    public static final String EMAILACTIVATE_TABLE_NAME = "email_act_registration";

    public static final String EMAILDEACTIVATE_FORM_KEYWORD = "email_deact";
    public static final String EMAILDEACTIVATE_TABLE_NAME = "email_deact_registration";
    //public static final String GOV_FIRST_COORD = "amishra@nic.in";// to be uncommented in production
    public static final String DNS_GOV_FIRST_COORD = "preeti.nhq@nic.in,raheja_preeti@yahoo.co.in";
    public static final String COORDINATOR_PENDING = "Pending with Coordinator";
    public static final String MANUAL = "Manual"; // line added by pr on 29thjan18
    public static final String VPN_BULK_FORM_KEYWORD = "vpn_bulk";
    public static final String CA_REJECTED = "Rejected by RO/Nodal/FO";
    public static final String DIST_FORM_KEYWORD = "dlist";
    public static final String CA_PENDING = "Pending with RO/Nodal/FO";
    public static final String ROLE_SUP = "sup";
    //public static final String NIC_FIRST_COORD = "rsm@nic.in,prakash@nic.in,bkd@nic.in"; // to be uncommented in production
    public static final String DNS_NIC_FIRST_COORD = "preeti.nhq@nic.in,rahejapreeti@gmail.com";
    public static final String NKN_BULK_FORM_KEYWORD = "nkn_bulk";
    public static final String LDAP_TABLE_NAME = "ldap_registration";
    public static final String DA_REJECTED = "Rejected by DA-Admin"; // line added by pr on 15thmar18
    public static final String MAIL_ADMIN_REJECTED = "Rejected by Admin";
    public static final String IMAP_TABLE_NAME = "imappop_registration";
    public static final String SINGLE_FORM_KEYWORD = "single";
    // start, code added by pr on 8thjan19
    public static final String US_PENDING = "Pending with Under Secretary and above";
    // end, code added by pr on 8thjan19
    public static final String COMPLETED = "Completed";
    public static final String SUPPORT_REJECTED = "Rejected by Support";
    public static final String COORDINATOR_REJECTED = "Rejected by Coordinator";
    public static final String SUPPORT_PENDING = "Pending with Support";
    public static final String IP_FORM_KEYWORD = "ip";
    //public static final String GEM_DA_ADMIN = "gemapplicant@gem.gov.in"; // line added by pr on 21stfeb18 
    public static final String GEM_DA_ADMIN = "lily.prasad@gem.gov.in"; // above line modified by pr on 31stjul19
    public static final String GEM_FORM_KEYWORD = "gem";
    public static final String WIFI_TABLE_NAME = "wifi_registration";
    public static final String US_EXPIRED = "Under Secretary and above Link Timeout"; // same terminology has been mentioned in CA.js
    public static final String DNS_BULK_CNAME = "dns_bulk_cname";
    public static final String DNS_BULK_MX = "dns_bulk_mx";
    public static final String DNS_BULK_SPF = "dns_bulk_spf";
    public static final String DNS_BULK_SRV = "dns_bulk_srv";
    public static final String DNS_BULK_TXT = "dns_bulk_txt";
    public static final String DNS_BULK_PTR = "dns_bulk_ptr";
    public static final String DNS_BULK_UPLOAD = "dns_bulk_upload";
    public static final String DNS_BULK_DMARC = "dns_bulk_dmarc";
    public static final String SERVICE_OWNERS_TABLE = "service_owners";
    public static final String FINAL_AUDIT_TRACK = "final_audit_track";
}
